### PR TITLE
Wheel colliders 2 electric boogaloo

### LINKED ISSUE #243: Implement Basic Wheel Colliders
Implement basic wheel colliders on the car model and see how they perform.

### LINKED ISSUE #244: Tweak Suspension Settings
The suspension on the wheel colliders is currently too bouncy. It needs to be dampened and tweaked to be a bit more rigid and make the wheels a little more realistic.

### LINKED ISSUE #245: Change acceleration settings
The care feels a bit sluggish with the wheel colliders, some settings need changing to make it more responsive.

Accelerate faster but lower top speed.

### LINKED ISSUE #246: Remaster drifting
The old drift system doesn't work with the new wheels.

The old drifting actually worked quite well and it would be nice to emulate a similar feel.

### LINKED ISSUE #247: Redo the jumping
Similar to the drifting, this needs tweaking to work with the new system.

### LINKED ISSUE #248: Driving on Road should feel "better" on road
Encourage people to drive on the roads by making the driving feel "better" when on a road.

"Better" should probably mean increased acceleration.

We agreed that driving off-road should not feel awful though.

### PR DESCRIPTION
**Pull request by Keywarn**
Gotta love game dev, third time lucky.

New improved driving with wheel colliders (again).

Jumping and drifting work. I think the drift feels a little less arcade-like but I think for now it's ok.

Please play before approving.

### CODE REVIEW

**Comment by adeeg** [comment]
driving actually feels great to play. A+++

would say camera still feels bad but something that can be sorted later

**Review by adeeg — APPROVED** [review]

**Comment by liamdalg** [comment]
this is great :) is it possible to improve acceleration from standing still? also if you crash into something it takes forever for you to be able to reverse again

**Comment by Keywarn** [comment]
> driving actually feels great to play. A+++
> 
> would say camera still feels bad but something that can be sorted later

Yeah, @Dimmitsaras is working on that on a separate branch.

**Comment by Keywarn** [comment]
> this is great :) is it possible to improve acceleration from standing still? also if you crash into something it takes forever for you to be able to reverse again

Yeah, the acceleration still bothers me a bit, I've played with the friction curves but can't get it perfect. Might tweak it but I think this is at least better for now?

**Pull request merged**
