### PR TITLE
Baked Lightmap

### PR DESCRIPTION
**Pull request by liamdalg**
Adds baked lightmaps and GI to the scene, makes it look much better. It's a bit bright atm but we can change it once we move to URP.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
great job !!!

**Comment by liamdalg** [comment]
One sec lemme check it on my laptop

**Comment by ghost** [comment]
bro this lightmap do be looking pretty baked tho 🍁 🍁 🤣 🤣 🚭

**Comment by liamdalg** [comment]
Do not merge this, need to test performance on lab

**Review by RileyEv — CHANGES_REQUESTED** [review]
Pls no vscode

**Comment by RileyEv** [comment]
Eduroam cannot handle this pr 🤷‍♂️

**Comment by Keywarn** [comment]
Will the baked map work with URP? Or does it require a new baking procedure?

**Comment by liamdalg** [comment]
Same procedure, but I'll rebake anyway because of performance

**Comment by RileyEv** [comment]
@liamdalg are redoing this today?

**Comment by liamdalg** [comment]
I can do yeah if we want it for the demo

**Comment by RileyEv** [comment]
yeah go for it, made it look a lot nicer

**Comment by liamdalg** [comment]
I think it's alright to merge, we just need to build on medium settings rather than ultra (I can set it up when I come into uni)

**Review by Keywarn — APPROVED** [review]

**Review by Keywarn — APPROVED** [review]

**Review by RileyEv — APPROVED** [review]

**Pull request merged**
