### PR TITLE
Car indicator

### LINKED ISSUE #210: RenderToMinimap Colour
Implement an overlay colour for the `RenderToMinimap` script which tints the sprite indicator.

### PR DESCRIPTION
**Pull request by liamdalg**
Small PR :)

Adds a better car indicator, removes old scripts, and adds the ability to tint the indicators.

Resolves #210

### CODE REVIEW

**Review by ChrisGora — APPROVED** [review]
I support your refusal to use the American "Color" 👍🏼

**Comment by RileyEv** [comment]
Did you put the bit in that fixes the compiling issue?

**Comment by liamdalg** [comment]
> Did you put the bit in that fixes the compiling issue?

No, but I can if you like

**Comment by RileyEv** [comment]
Yeah would probably be good if it went in asap

**Pull request merged**
