### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by RileyEv**

### CODE REVIEW

**Comment by Keywarn** [comment]
I don't really mind and don't have too much of an issue but if it did ever happen, do we want people to be able to sell our game?

**Review by Keywarn — APPROVED** [review]

**Comment by RileyEv** [comment]
> I don't really mind and don't have too much of an issue but if it did ever happen, do we want people to be able to sell our game?

probably not and MIT aint gonna stop that 🤔

**Comment by liamdalg** [comment]
what if we make a legit good game

**Comment by ghost** [comment]
then everyone can play it for free ☭

**Pull request merged**
